### ISSUE TITLE
Microservices testing (API)

### ISSUE THREAD

**Issue by Semerjyan** [QT-Lab/tech-meetups#4]
Let's talk about how to automate testing microservices with and without APIs.

**Comment by amuradyan** [comment]
Microservices are a very broad and technical topic. Maybe you have a specific feature to be tested in mind?

I've never had experience with microservices /but will soon/, so I looked around for some reading material. I have not read all of what I found, but maybe you'll want to look through them too, so I'll leave a list below. _NOTE_ though, that they may be of poor quality.

I'm also thinking we could try to setup and run a microservice system. I've found [this](https://developers.redhat.com/blog/2016/07/27/have-your-own-microservices-playground), but did not try it out still. The whole process is technically colorful so will require quite some time and preparation. 

----
Reading material

1. Chapters 9 and 10 on testing microservices from the [_Microservices patterns_ book](https://microservices.io/book) /looks good/
2. [_Microservice testing_](https://martinfowler.com/articles/microservice-testing/) /from [Thoughtworks](https://www.thoughtworks.com/), should be good/
3. [_Microservices Testing Strategies, Types & Tools: A Complete Guide_](https://www.simform.com/blog/microservice-testing-strategies/) /probably is not, wont rely on this too much/
4. _Testing Microservices: an Overview of 12 Useful Techniques_ [Part 1](https://www.infoq.com/articles/twelve-testing-techniques-microservices-intro/) | [Part 2](https://www.infoq.com/articles/twelve-testing-techniques-microservices-tradeoffs/) | [Part 3](https://www.infoq.com/articles/testing-techniques-microservices-use-cases/) /from [InfoQ](https://www.infoq.com/), may be good/

**Comment by Semerjyan** [comment]
Thanks for sharing the information you found!
In that case, let's not dive into microservices as part of our technical meetings. I think we can talk sometime in the future, when you already have experience with microservices, and I will review the materials you found.

May I suggest considering BDD as a new topic? What you think, should I open a new issue for BDD?

**Comment by amuradyan** [comment]
@Semerjyan I've read the (2) and (3) from the list in my previous comment and the latter is a rather liberal retelling of the former. I /strongly/ suggest you skip (3) but read (2), which is a really good survey of the topic.

I say we don't postpone the talk based on my practical experience. I'll get back to you once I read the chapters from the microservices book /I'll try to do it by the end of this week/, and we'll decide if we are interested in me retelling you /guys/ what I've learned.

> May I suggest considering BDD as a new topic? What do you think, should I open a new issue for BDD?

BDD sounds great and yes, you should open an issue, so we have a separate discussion space for that.

**Comment by Semerjyan** [comment]
> I say we don't postpone the talk based on my practical experience. I'll get back to you once I read the chapters from the microservices book /I'll try to do it by the end of this week/, and we'll decide if we are interested in me retelling you /guys/ what I've learned.
> 
 Sounds good, thanks))) I will also read the materials you mentioned by the end of this week
 
> BDD sounds great and yes, you should open an issue, so we have a separate discussion space for that.
>
BDD issue open
