### ISSUE TITLE
BDD (Behavior-Driven Development) testing

### ISSUE THREAD

**Issue by Semerjyan** [QT-Lab/tech-meetups#7]

**Comment by amuradyan** [comment]
@Semerjyan Could you elaborate more on what you are interested in?

On a related note, have you seen the _Automation Pandas_ articles on [BDD](https://automationpanda.com/bdd/)? It's a pretty big collection of interesting resources and it helped me a lot when I was working on one of our projects. 

Are you familiar with [Gherkin](https://cucumber.io/docs/gherkin/reference/)?

**Comment by Semerjyan** [comment]
@amuradyan 
> @Semerjyan Could you elaborate more on what you are interested in?

I started working on a BDD project (using Cucumber) and it's all very important to me.

> On a related note, have you seen the _Automation Pandas_ articles on [BDD](https://automationpanda.com/bdd/)? It's a pretty big collection of interesting resources and it helped me a lot when I was working on one of our projects.

No, I didn't know about it, but I already found it and will investigate

> Are you familiar with [Gherkin](https://cucumber.io/docs/gherkin/reference/)?

I just started the process of understanding :D
